# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b605b412a4111d284ac5dc303fbd628d43d6aba12d4aaf872d54512d2401f530718d55ea015e30cbc6bbc55e0fdd69b7728f7a7a5e24eda73e28f10b93e483c8

test:
  secret_key_base: 520192a2f2e156050c03ce3666cfe40343686cdd1413c1baeaa1d1f9683417058e1356d503f941506ddb3506651ac7441921ae72be8311b376aa234c86079d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
